# Discovery script - test questionable item constants
quick_print("Carrot_Seed:", num_items(Items.Carrot_Seed))
quick_print("Pumpkin_Seed:", num_items(Items.Pumpkin_Seed))
quick_print("Sunflower_Seed:", num_items(Items.Sunflower_Seed))
quick_print("Water:", num_items(Items.Water))
quick_print("Fertilizer:", num_items(Items.Fertilizer))
quick_print("Egg:", num_items(Items.Egg))
quick_print("Cactus:", num_items(Items.Cactus))
quick_print("Cactus_Seed:", num_items(Items.Cactus_Seed))
quick_print("Bone:", num_items(Items.Bone))
